{
 "title": "nvitop-dashboard",
 "description": "Grafana Dashboard built by `nvitop-exporter`.",
 "tags": [
  "nvitop",
  "nvitop-exporter",
  "prometheus",
  "nvidia",
  "gpu",
  "gpu process",
  "gpu monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(hostname)" } },
   { "name": "username", "query": { "query": "label_values(username)" } }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Processes",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_cpu_percent_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_rss_memory_MiB{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_memory_MiB{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_sm_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_memory_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_encoder_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_decoder_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_running_time_Second{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_info_info{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "host_cpu_percent_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} CPU (%)"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 11, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_utilization_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}} (%)"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_memory_percent_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}} (%)"
    }
   ]
  },
  {
   "title": "Host Virtual Memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "host_virtual_memory_percent_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} MEM (%)"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "host_cpu_percent_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "host_load_average_1m_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} (1m)"
    },
    {
     "expr": "host_load_average_5m_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} (5m)"
    },
    {
     "expr": "host_load_average_15m_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} (15m)"
    }
   ]
  },
  {
   "title": "Host Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "host_virtual_memory_used_MiB{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Host Swap Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "host_swap_memory_used_MiB{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "System I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Host Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by(hostname) (rate(host_net_io_rx_data_MiB{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} RX"
    },
    {
     "expr": "sum by(hostname) (rate(host_net_io_tx_data_MiB{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} TX"
    }
   ]
  },
  {
   "title": "Host Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by(hostname) (rate(host_disk_io_read_data_MiB{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} Read"
    },
    {
     "expr": "sum by(hostname) (rate(host_disk_io_write_data_MiB{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} Write"
    }
   ]
  },
  { "title": "Accelerator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_utilization_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "gpu_memory_used_MiB{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU PCIe RX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "gpu_pcie_rx_throughput_MiBps{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU PCIe TX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "gpu_pcie_rx_throughput_MiBps{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU NVLink RX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "gpu_nvlink_total_rx_throughput_MiBps{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU NVLink TX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "gpu_nvlink_total_tx_throughput_MiBps{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_power_usage_W{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_temperature_C{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  }
 ]
}